[/]
control-center=['<Super>i']
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/']
home=['<Super>f']
rotate-video-lock-static=@as []
screensaver=['<Super>Escape']
terminal=['<Super>t']
www=['<Super>b']

[custom-keybindings/custom0]
binding='<Shift><Control>space'
command='1password --quick-acess'
name='1password'

[custom-keybindings/custom1]
binding='<Shift><Super>y'
command='snap run chromium --profile-directory=Default --app-id=agimnkijcaahngcdmfeangaknmldooml'
name='Youtube'

[custom-keybindings/custom2]
binding='<Shift><Super>a'
command='snap run chromium --profile-directory=Default --app-id=fmpnliohjhemenmnlpbfagaolkdacoja'
name='Claude'

[custom-keybindings/custom3]
binding='<Shift><Super>z'
command='snap run chromium --profile-directory=Default --app-id=hnpfjngllnobngcgfapefoaidbinmjnm'
name='Whatsapp'

[custom-keybindings/custom4]
binding='<Shift><Super>w'
command='snap run chromium --profile-directory=Default --app-id=mibgiapfolionpapiffjmagepkdbmdjn'
name='Wanikani'

[custom-keybindings/custom5]
binding='<Shift><Super>t'
command='telegram-desktop'
name='Telegram'
